### ISSUE TITLE
Tokio support

### ISSUE THREAD

**Issue by tehmatt** [polyfloyd/rust-id3#100]
Have you thought about what this might look like and whether you'd accept a patch adding it?

I have an application using id3 on a pretty slow NFS volume, so have a theory that async support would let me hide a bunch of latency when reading tags for my library.  I haven't ever done a sync -> async conversion before, but am planning to give it a try and see if it's an improvement for my app, and it seems like it could be worth it for other people.

**Comment by polyfloyd** [comment]
Yeah, this does sound like a useful feature. I have not really thought about how this would be built, but most of the internal interfaces of id3 use io::Read. So using asynchronous IO to look up the start and end, then reading the whole thing into a buffer would probably work.

**Comment by tehmatt** [comment]
That was pretty easy, so I implemented it as #102.  Pretty decent win for my local setup, but I haven't tried on the NFS volume where I'd expect it to be even better.
