### ISSUE TITLE
In the "Creating a new tag, overwriting any old tag" example, why using both set_album() and add_frame()??

### ISSUE THREAD

**Issue by AndreasDavour** [polyfloyd/rust-id3#108]
The example looks confusing. Is there something in that use case that necessitates using both methods to manipulate the frame for album?

**Comment by polyfloyd** [comment]
No. If setting the album or a simple text value like that is all that is needed, then set_album and the likes will do fine.

However, there may be situations where one needs to alter a frame that is not properly implemented or even out-of-spec. The example is meant to showcase the existence of functions that permit more fine grained control.
