### ISSUE TITLE
Consider making `Tag::read_from[...]` functions return `Result<Option<Tag>>`

### ISSUE THREAD

**Issue by GBujak** [polyfloyd/rust-id3#122]
Consider making `Tag::read_from[...]` functions return `Result<Option<Tag>>` and return `Ok(None)` when a file has no tag, but otherwise there were no errors. I think most users would like to handle errors and files without tags differently and at the moment you have to match on the `id3::Result::kind`

```rs
    /// An error kind indicating that the reader does not contain an ID3 tag.
    NoTag,
```

How I'm doing it at the moment:
```rs
    let tag = {
        let tag_res = Tag::read_from_path(path);
        match tag_res {
            Ok(tag) => Ok(tag),
            Err(e) => {
                if let ErrorKind::NoTag = e.kind {
                    Ok(Tag::new())
                } else {
                    Err(e)
                }
            }
        }
    }?;
```

**Comment by polyfloyd** [comment]
Good idea! There already is a `partial_tag_ok` function, I added  the `no_tag_ok` helper function using the same convention.

**Comment by GBujak** [comment]
damn, that was quick, thanks a lot 👍
