### ISSUE TITLE
Writing tags to aiff results in broken files on Apple Silicon

### ISSUE THREAD

**Issue by Esgrove** [polyfloyd/rust-id3#123]
Works on Windows but produces corrupt / broken files on Apple Silicon. Edit: Same thing happens on an Intel Mac. macOS Sonoma 14.2.1 in both cases. Happens with every `.aif` file I have tried so far (1000+).

I double checked the files are good before updating the tags using this library. Mp3 files work but aif files come out broken on macOS.

Here are the relevant parts from my program using this library:

```rust
fn read_tags(track: &Track) -> Option<Tag> {
    let result = match track.format {
        FileFormat::Aif => Tag::read_from_aiff_path(&track.path),
        FileFormat::Mp3 => Tag::read_from_path(&track.path),
    };
    match result {
        Ok(tag) => Some(tag),
        Err(Error {
            kind: ErrorKind::NoTag, ..
        }) => {
            println!("{}", format!("No tags: {}", track).yellow());
            Some(Tag::new())
        }
        Err(err) => {
            eprintln!("{}", format!("Failed to read tags for: {}\n{}", track, err).red());
            None
        }
    }
}
```

```rust
let mut tag = match Renamer::read_tags(track) {
    Some(tag) => tag,
    None => continue,
};

// formatting stuff inbetween...
            
tag.set_artist(formatted_artist.clone());
tag.set_title(formatted_title.clone());
tag.write_to_path(&track.path, id3::Version::Id3v23)
    .context("Failed to write tags")?;
```

Sidenote: Should `read_from_path()` work for aif too? I did not for me, which is why I had to result to calling `read_from_aiff_path`. It was not obvious from the documentation that `read_from_path()` only works for mp3 🤔

**Comment by polyfloyd** [comment]
Interesting. My first thought was something related to endianness, but if it happens on both Apple ARM and Intel x86 then that may not be it.

Could you please post an original file and the updated file produced by rust-id3 so I can compare?


The read functions are indeed distinct. `read_from_path` tries to locate an ID3 tag as a prefix of the actual content of the file. This style is what MP3 uses, but I have seen FLAC and WAV files that also have such tags, even though those formats have different conventions.

If this distinction was unclear from the docs then it is worth it to add a note :)

**Comment by Esgrove** [comment]
Did some more systematic testing now. I exported a 2 second noise sample from Ableton Live 11 in both aif and mp3 format, and also in both 44.1 and 48 kHZ samplerates too cause why not.

I then created three test sets with copies of these files:
1. no tag data (as they came out of Ableton)
2. Basic artist and title tags set using the Mp3tag software
3. The basic tag files analyzed in my DJ software (Serato DJ Pro) that sets additional tag data like key, and custom field like playcount and track waveform analysis data.

My suspision was that this number 3 was causing the issues since all the files I have processed have been analyzed in the DJ software earlier...

However, **all three sets came out broken** when writing the tags with this library 😞 Mp3 files work but all aif files are broken.

Here are the test sets, both the input files before running through my program and broken output files.
https://www.dropbox.com/t/NIevUgXXEX5WEXBk

**In Mp3tag:**

Input 1:
<img width="1580" alt="input1" src="https://github.com/polyfloyd/rust-id3/assets/16880853/03442512-79b8-44f9-8601-27bae99c5295">

Input 2:
<img width="1533" alt="input2" src="https://github.com/polyfloyd/rust-id3/assets/16880853/56153ce9-4dfa-49c0-b90b-caa7140e7c3a">

Output 1:
<img width="1699" alt="output1" src="https://github.com/polyfloyd/rust-id3/assets/16880853/bc4a3731-46dd-496d-ac6f-6d73b695eb33">

**Comment by Esgrove** [comment]
Context: I am a professional audio engineer and DJ (on top of my day job doing software development), and I wrote a [CLI helper tool](https://github.com/Esgrove/track-rename) to format my music tags and file names like I want to have them. Originally written in Python using pytaglib (a thin wrapper to C++ taglib), but a few things annoy me about the Python version + I love Rust so I made a Rust version recently.

**Comment by polyfloyd** [comment]
![2024-02-16_19-47](https://github.com/polyfloyd/rust-id3/assets/4839878/4ddc171e-1d10-4f17-b755-b515c0d21258)

This is the diff between the `output/ID3TEST1_NOTAGS/16-44.aif` and `output/ID3TEST2_BASICTAGS/16-44.aif`. The NOTAGS file has an ID3 tag as header, the second file has the same ID3 header and an additional ID3 tag at the end of the file.

This is in line with how the id3 library currently functions. The implementation of the AIFF format expects the tag to be in a distinct chunk and not be a header in front of the audio.

Could you try to write the metadata using the MP3 function? MP3 stores the metadata as a header, so that should pick up on the header that is already there. It could be that your software may not know what to do with the AIFF chunk or duplicate ID3 metadata.

There is definitely some work to be done here on my end, if ID3 headers are valid for the AIFF (and other formats?) then it should prefer the location of the tag that is already there, if any.

**Comment by polyfloyd** [comment]
Or, try my patch in the magic-format-detection branch. This should detect whether there is a header-style tag present

**Comment by Esgrove** [comment]
I tried with the magic branch using 
```shell
id3 = { git = "https://github.com/polyfloyd/rust-id3", branch = "magic-format-detection" }
```

With this branch everything works and I get working aiff files 👍🏻 

If using `read_from_path`, aiff files return `ErrorKind::NoTag` but then writing tags to aiff works after my code falls back to parse the artist and title from the filename, resulting in working aiff files though.

**Comment by polyfloyd** [comment]
Great! I have also implemented format detection for the read functions. Let me know if that works for you

**Comment by Esgrove** [comment]
Yes, now `read_from_path` works for aiff too with the latest commit. Thanks!
