### ISSUE TITLE
MSRV Policy & CI

### ISSUE THREAD

**Issue by pinkforest** [polyfloyd/rust-id3#127]
It would be helpful to both set policy and CI to test the MSRV e.g. to maybe help issues like this:
- #126

**Comment by polyfloyd** [comment]
Yes, this would be good to have. But what?

Does Rust itself have a guideline for how long to support older versions? What do other crates have? What Rust version is most commonly shipped by Linux distro's?

I often work with Go too, which officially support the latest and the previous stable version, which is about 1 year with Go's release schedule.

On thing that I am definitely will be factoring in is maintenance burden, as I prefer to keep this project alive and well but not spend too much time on it :grimacing:

**Comment by pinkforest** [comment]
With binaries it's less of an issue and mainly hangs on what ever the distros have yes.

But with libraries the problem becomes all the downstream consumers especially if 10 layers down the dependencies we are pretty conscious when we raise MSRV.

My motivation here was because my builds for audiotags broke as downstream library consumer + who ever was using audiotags as a library downstream here so I was hoping to have a standard(ish) library style policy and I think just setting initial MSRV to 1.65 would be safe bet reflecting what most ecosystem is now currently at that provides enough flexibility.

We can add MSRV test with -Z minimal-versions nightly Cargo.lock generate will test it in CI properly automatically e.g. what we use in curve25519-dalek - 

I've already sent a PR for that #128 too as well as quick placeholder fix #129 to resolve the build errors downstream if you're amenable to this solution.

Crucial bit in the MSRV Policy would be to bump minor patch version when ever MSRV gets bumped so downstream knows the MSRV was bumped giving them informed choice to stay at lower version until they are ready to go over the MSRV bump.

As to maintenance burden the MSRV test in CI handles most of it so if there is at least no accidental MSRV bump so we know it when happens consciously and then signal minor patch version that can be bumped at downstream when needed.

See policy we use elsewhere e.g. curve25519-dalek MSRV policy: https://github.com/dalek-cryptography/curve25519-dalek/tree/main/curve25519-dalek#minimum-supported-rust-version

**Comment by polyfloyd** [comment]
Alright, thank you for picking this up.

We have not really established a real policy, so I'll support v1.65 as long as it requires not too much effort. If there ever comes a sort of recommendation from the Rust org/community then id3 will probably follow that.
