### ISSUE TITLE
Readme Update - running tests depends on installed ffmpeg

### ISSUE THREAD

**Issue by jakubbalas** [polyfloyd/rust-id3#131]
Hey hey, 

I was trying to run tests on my system where I didn't have ffmpeg installed and it was throwing a bit of obscured message like 'no such file or directory' in `test_issue_39` and one other. It was because I was missing that dependency. 

Would it be possible to add it to Readme somewhere please ? 

Thank you

**Comment by polyfloyd** [comment]
Oh yes, I can certainly do that!

I is probably also worth it to have this check be less cryptic :grimacing:
