### ISSUE TITLE
Support for multiple artists in ID3v2 2.3 & 2.4

### ISSUE THREAD

**Issue by michael-ball** [polyfloyd/rust-id3#20]
The ID3v2 2.3 specification states that multiple artists can be specified in the TPE1 frame by separating with a "/" character.

In the ID3v2 2.4 specification any T* frame (apart from TXXX) can contain multiple values separated by a NULL character (dependant on character encoding).

Do you plan to support this? I'm happy to work on it and submit a pull request if you're interested in this.

**Comment by polyfloyd** [comment]
Yes, I'd be happy to accept a PR implementing this functionality. :)

To help you getting started, this is roughly what needs to be done:
* Think of a public interface. This can be simply a documenting NULL as a separator char or something more complex. `src/frame/content.rs` would be a good place to start.
* Modify the encoder/decoders in `src/stream`
* Create some tests, to make sure that it works and keeps working.

**Comment by polyfloyd** [comment]
Fixed in 92c783b7 :)
