### ISSUE TITLE
MLLT support

### ISSUE THREAD

**Issue by ahti** [polyfloyd/rust-id3#24]
Would you consider adding a content type for reading and writing [MLLT](http://id3.org/id3v2.3.0#sec4.7) tags?

The quirky thing about this tag is probably that the reference entries contain integers that can be dynamically sized, up to 256 bit. Their combined size has to be a multiple of four, but it seems like the integers themselves could be anything from 1 to 255 bits long (or maybe even 0 to 256? I'm not quite sure how to interpret the tag docs).

So supporting this would probably mean a fair amount of bit-twiddling and depending on something like [num-bigint](https://github.com/rust-num/num-bigint).

A middle way could be to support the meta fields, but decode the references into a single blob that consumers can then further encode/decode themselves.

**Comment by polyfloyd** [comment]
I think it's possible to manually encode and decode these tags using raw `Content::Unknown` frames.

However, we would happily accept a patch to add proper support for this feature. :)

**Comment by ahti** [comment]
Yes, that is what I have done for now.

For anyone that needs MLLT, [this is my implementation](https://github.com/vorleser/vorleser-server/blob/ba5ba2bd82451bee96a0e39c47638cbf5afd922f/src/helpers/mllt.rs), which also generates the mllt table from mp3 frames. It has a fixed number of bits for size and the code isn't very pretty, but it works.

**Comment by polyfloyd** [comment]
MLLT support has been implemented in 0ea0a7ff which will be released with 1.0
