### ISSUE TITLE
Not all tags are processed

### ISSUE THREAD

**Issue by graeme3317** [polyfloyd/rust-id3#46]
Hi,
When using the library I noticed that some tags do not have any value even though other tools show values.

I  first thought that the change below fixed it:

`diff --git a/src/stream/tag.rs b/src/stream/tag.rs
index 552954c..3d495eb 100644
--- a/src/stream/tag.rs
+++ b/src/stream/tag.rs
@@ -93,7 +93,7 @@ pub fn decode(mut reader: impl io::Read) -> crate::Result<Tag> {
         }
     } else {
         let mut tag = Tag::new();
-        while offset < tag_size + tag_header.len() {
+        while offset < tag_size * tag_header.len() {
             let rs = frame::decode(
                 &mut reader,
                 version,
`
When I debugged it I could see that, for the mp3 file I was using, tag_header contained 10 items, but only the first 6 were being processed because the while loop was exited too early.

With the above fix, 'cargo test' passed and a test I had added that previously failed now passed.

I now think my fix isn't right because it assumes that all tags are the same size and that doesn't seem to be true.
My current guess is that an APIC tag with a large amount of data is  the cause of the problem.

What always happens is that the loop in stream/tag.rs exits too early.

Regards,

Graeme

**Comment by graeme3317** [comment]
I think I may have corrupted the mp3 files which caused the problems. I'm not sure but don't want to waste your time.

**Comment by polyfloyd** [comment]
Np! Thank you for raising issues instead of suffering them, even they turn out to be not a bug at all ;)
