### ISSUE TITLE
remove year, date_recorded, date_released

### ISSUE THREAD

**Issue by TianyiShi2001** [polyfloyd/rust-id3#49]
All readable and settable fields are also removable, except for these three fields. Is there a particular reason for this? If not I'll make a PR to add a `.remove_*()` method for these three fields.

**Comment by polyfloyd** [comment]
The named functions are fairly incomplete and written based on how common these fields are, I think. After inheriting this codebase, this was not a concern of mine.

Feel free to submit a PR :)

**Comment by TianyiShi2001** [comment]
I agree that exact dates are not common but IMO 'year' is a quite essential attribute (probably because I'm coming from an academic background and all bibliography entries must have a year).
