### ISSUE TITLE
AIFF support

### ISSUE THREAD

**Issue by bascurtiz** [polyfloyd/rust-id3#52]
1st of all, love the library, works great!
But we're hoping to use it aswell with AIFF format, since it's using ID3, but with offsets.
Keep up the good work!

**Comment by thorfinnrowle** [comment]
Aiff Support would be dope, Serato & Rekordbox support of AIFF data is better than FLAC from a tagging point of view.

**Comment by polyfloyd** [comment]
Yes! This seems like a good addition :+1: 

Unfortunately I currently can not spare the time to develop this. If this is needed sometime soon, I would be happy to give a few pointers to whoever is willing whip up a patch :)

**Comment by polyfloyd** [comment]
Implemented by @marekkon5 in 5adbdbe4852b2f984deadd892fd558c70ffa679c :+1:
