### ISSUE TITLE
AIFF parser does not handle padding

### ISSUE THREAD

**Issue by gahag** [polyfloyd/rust-id3#65]
Recently, we have implemented WAV support in [Polaris](https://github.com/agersant/polaris/) using this crate, which worked like a charm. By noticing there is also the new AIFF API, we tried to also implement support for such format. When writing our tests, we noticed that rust-id3 does not handle padding in AIFF chunks, which causes it to miss the ID3 chunk if there is an odd-sized preceding chunk. Further, the code for writing tags may corrupt the file if padding is present.

**Comment by gahag** [comment]
As both formats are very similar, maybe we can rework the WAV code so that it'll be able to handle AIFF files too. I'm willing to give it a shot if you think it is a good idea.

**Comment by polyfloyd** [comment]
By all means, go ahead :)
