### ISSUE TITLE
Use of unstable stream_position

### ISSUE THREAD

**Issue by Ghosty141** [polyfloyd/rust-id3#68]
For a project of mine I'm using rust (stable) and when building I get the following message:
```
error[E0658]: use of unstable library feature 'seek_convenience'
...
let id3_tag_pos = file.stream_position()?;
```

When checking out the function it says "this is equivalent to self.seek(SeekFrom::Current(0))." which would work in stable.
How about replacing the `stream_position` calls with `seek(SeekFrom::Current(0))` to make this library fully compatible with stable rust? 

Have you tried this/what is the reason this unstable feature is needed?

**Comment by polyfloyd** [comment]
At first I was confused because the CI should have caught this. But `stream_position` has been stabilized in Rust 1.51, which is the latest stable version. Updating your installed Rust version should fix it :+1:

**Comment by Ghosty141** [comment]
Oh I didn't notice, thanks 👍
