### ISSUE TITLE
m4a files fail to be parsed

### ISSUE THREAD

**Issue by TurtleP** [polyfloyd/rust-id3#71]
Hi,

I've been learning rust and wanted to mess around with this library. However, all my media is in an m4a format from iTunes. The following seems to not work whatsoever:

```rust
use std::path::Path;

use id3::{Tag, Version};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // this is relative to the current directory
    let path = Path::new("./10 I Write Sins Not Tragedies.m4a");

    let tag = Tag::read_from_path(path)?;

    // Get a bunch of frames...
    if let Some(artist) = tag.artist() {
        println!("artist: {}", artist);
    }

    if let Some(title) = tag.title() {
        println!("title: {}", title);
    }

    if let Some(album) = tag.album() {
        println!("album: {}", album);
    }

    // Get frames before getting their content for more complex tags.
    if let Some(artist) = tag.get("TPE1").and_then(|frame| frame.content().text()) {
        println!("artist: {}", artist);
    }

    Ok(())
}
```

When I run this, I get `Error: NoTag: reader does not contain an id3 tag`. Though a similar library written in python *can* find the id3 tag for this file and all the others. I'm not sure if this is specifically due to the m4a format or what, but If there's something I did wrong, please let me know.

**Comment by polyfloyd** [comment]
Could you please attach a problematic file to this issue?

**Comment by TurtleP** [comment]
Here is the file in the example. Hopefully it's okay to share, as it's directly from my iTunes library.
[id3_issue_file.zip](https://github.com/polyfloyd/rust-id3/files/6850637/id3_issue_file.zip)

**Comment by polyfloyd** [comment]
Thanks, I got it.

There is no ID3 tag in this file. I did some quick searching and concluded that M4A has a different format to store its metadata.

I had a glance at the list of crates that have ID3 as dependency, you could give this library a shot: https://crates.io/crates/audiotags

**Comment by TurtleP** [comment]
Interesting then, I'll take a look. Thanks!
