### ISSUE TITLE
Combine TIPL:producer and TIPL:engineer?

### ISSUE THREAD

**Issue by jamesyoungman** [polyfloyd/rust-id3#72]
It appears that I cannot write both TIPL:producer and TIPL:engineer to the same tag.

That is, I think that if I write

```
    tag.add_frame(Frame::with_content("TIPL", Content::Text("producer\u{0}Barney")));
    tag.add_frame(Frame::with_content("TIPL", Content::Text("engineer\u{0}Wilma")));

```
then only one of these is preserved.   Is this deliberate?   Is there a workaround?

The letter of the [spec](https://id3.org/id3v2.4.0-frames) seems a little unclear on this.  Section 4.2 says:

> The text information frames are often the most important frames,
> containing information like artist, album and more. There may only be
> one text information frame of its kind in an tag. All text
> information frames supports multiple strings, stored as a null
> separated list, where null is reperesented by the termination code
> for the charater encoding. All text frame identifiers begin with "T".

 In particular, the word kind does not seem to be defined.

**Comment by polyfloyd** [comment]
The spec is indeed ambiguous on some subjects. However, in my interpretation "kind" can not be read as something other than "frame identifier" in this context.

So no, you may only set 1 TIPL frame in a tag. You do have some workarounds to choose from:
* Format the TIPL frame with multiple strings using 0-bytes to separate different values
* Use an Extended Text frame (TXXX) and use the frame's description to store different values

The best option depends on what other software will be reading your tag :)

**Comment by jamesyoungman** [comment]
The most widely-useful schema I know of is the one used by Musicbrainz Picard.  That specifies the use of both TIPL:producer and TIPL:engineer as being equivalent to the PRODUCER and ENGINEER Vorbis comments.  See [this equivalence table](https://picard-docs.musicbrainz.org/downloads/MusicBrainz_Picard_Tag_Map.html) for details.   

To be direct about it, lack of support for combining TIPL:producer and TIPL:engineer (and TIPL:arranger, TIPL:mix and TIPL:DJ-mix) makes id3-rs effectively read-only for quite a number of cases.

Using TXXX might work from a technical point of view, but that won't be successful from an interoperability point of view, as there is no consensus about how to represent the recording engineer, producer, etc. with the TXXX frame.

**Comment by polyfloyd** [comment]
How is `TIPL:engineer` encoded in the final file by Musicbrainz? Could you send over a sample?

**Comment by jamesyoungman** [comment]
Oh, this is interesting, I had clearly misinterpreted Picard's actual behaviour, probably as a result of seeing files whose metadata had been updated by my own code :)

Here's an example straight from Picard:

```
Frame {
     id: Valid(
         "TIPL",
    ),
    content: Text(
        "engineer\u{0}James Youngman\u{0}engineer\u{0}Jar-Jar Binks\u{0}producer\u{0}James Youngman\u{0}producer\u{0}Alan Smithee",
    ),
    tag_alter_preservation: false,
    file_alter_preservation: false,
},
```

I can also send you a copy of the file, but the above Debug representation from rust-id3 makes reasonably clear what's going on.

I believe that this means that the answer to my question is that you combine TIPL:producer and TIPL:engineer in a single TIPL frame, and that the NUL-separated pairs in the text portion of the frame are description/value pairs.   Hence a corrected version of the code I was asking about would have been:

```
    tag.add_frame(Frame::with_content("TIPL", Content::Text("producer\u{0}Barney\u{0}engineer\u{0}Wilma")));
```

**Comment by polyfloyd** [comment]
Great! Yes, this debug output is also clear to me.

The add_frame call looks a bit unwieldy though. I think it is time to add an API to conveniently add split strings.

**Comment by jamesyoungman** [comment]
Semantically I suppose there are two cases.

1. where the text value is simply a repeated field.  Such as, I think, TPUB.   AIUI, TXXX is also always like this.
2. where the text value is a sequence of key/value pairs, such as TIPL.

I think also UFID is a key/value pairs case, though I'm not certain of this partly because I haven't seen any examples with more than one value.   It's also an exception in another way I think, as it seems to be a text field not beginning with T.

Don't feel you need to keep this issue open for my benefit by the way, I'm happy that it can be closed.
