### ISSUE TITLE
GRP1 Writing

### ISSUE THREAD

**Issue by Marekkon5** [polyfloyd/rust-id3#78]
Hello, every time I wanna write a Text frame to `GRP1` I get `InvalidInput: Frame with ID GRP1 and content type Text can not be written as valid ID3`. Looking into the source code (`src/frame/mod.rs`):

```
... 48
        // The matching groups must match the decoding groups of stream/frame/content.rs:decode().
        match (id.as_str(), &self.content) {
            ("GRP1", Content::Text(_)) if id.starts_with('T') => Ok(()),
            (id, Content::Text(_)) if id.starts_with('T') => Ok(()),
... 53
```

Which makes no sense to me. `GRP1` will never start with `T`. Is there something I don't understand, or just a typo. Thank you.

**Comment by polyfloyd** [comment]
Hmm yes, that is definitely a typo. If it should be written as a Text frame the `if` check should not be there.

**Comment by Marekkon5** [comment]
Should I make a PR?

**Comment by polyfloyd** [comment]
Yes! Please do :)
