### ISSUE TITLE
Get the list of artists / genres more easily?

### ISSUE THREAD

**Issue by martpie** [polyfloyd/rust-id3#84]
Hello 👋 

First of all, I am very new to Rust (started a couple of days ago), so I may ask something stupid. 

I'm playing with rewriting [Museeks](https://museeks.io/) with Tauri (Rust), and I see some inconsistencies between the library I'm using with Node.js and this one, and I wanted to know if this was a limitation by design, or just a missing feature :)

Example: https://github.com/Borewit/music-metadata/blob/1e1bd78dc5abeea49dfe0402681f39da64aa60b4/lib/type.ts#L90-L93

A file can have multiple artists or genres, and when getting the genres of a track, everything gets joined, 

example: `["Rock", "Pop"]` becomes with `rust-id3` "RockPop".

<img width="883" alt="Screenshot 2022-05-11 at 19 17 46" src="https://user-images.githubusercontent.com/1311607/167908869-b2c2f96b-b805-4d5f-8434-990d3584ee1a.png">

Could `rust-id3` provide some helpers to return arrays instead? I think this could be done by adding plural methods `artist() -> artists()` so it's backwards compatible.

thanks in advance!

**Comment by polyfloyd** [comment]
Hi! This library supports having multiple values, but the API is indeed very minimal. You could use the following right now:
```
tag.get("TPE1").and_then(|frame| frame.text_values())
```
The specific standard that this library follows is to split on null bytes for ID3v2.4 and split on slashes for prior versions. I am not sure whether that is the same convention that this other library uses.

I like the idea of having functions for this, I'll leave this issue open for tracking.

**Comment by polyfloyd** [comment]
Yes, please! :)
