### ISSUE TITLE
Unified ID3v1/ID3v2 API

### ISSUE THREAD

**Issue by martpie** [polyfloyd/rust-id3#92]
Following the discussion on #86 on trying to unify the API with ID3 v1 and v2 in a single call.

I'm coming from @Borewit's awesome [`music-metadata`](https://github.com/borewit/music-metadata), which is more the scope of `rust-audiotags` than `rust-id3`, but is an [awesome source of inspiration](https://github.com/Borewit/music-metadata/tree/69d32cea31969dc728b2107519c432dc961df891/lib) when it comes to handling weird edgecases with file formats.

Some code pointers:

- [Unified `parseFile` function](https://github.com/Borewit/music-metadata/blob/69d32cea31969dc728b2107519c432dc961df891/lib/index.ts#L34-L56)
- [https://github.com/Borewit/music-metadata/blob/69d32cea31969dc728b2107519c432dc961df891/lib/id3v1/ID3v1Parser.ts#L155-L162](hasID3v1Header) util + [here](https://github.com/Borewit/music-metadata/blob/19366b896cbe4751eae48fc0473699c63d2050c6/lib/core.ts#L86-L96)

I usually work at a much higher level of abstraction (I build UIs, not interacting much low-level operating system stuff), so my knowledge is quite limited here, but if I can be of any help, please ask!

**Comment by Serial-ATA** [comment]
Sorry to promote here, but if you needed something inline with `music-metadata` I have a crate for this: https://github.com/Serial-ATA/lofty-rs.

**Comment by polyfloyd** [comment]
Hello again, I have written a new module that handles both format versions simultaneously. @martpie Could you check it out and tell me if this is how you would expect something like this to behave?

**Comment by martpie** [comment]
Will try tomorrow! What the name of the module?

**Comment by polyfloyd** [comment]
`v1v2`

**Comment by martpie** [comment]
🔥

<img width="909" alt="Screenshot 2022-06-10 at 14 44 31" src="https://user-images.githubusercontent.com/1311607/173066921-00c8a259-97c6-48aa-bb82-86d4805601ec.png">

If I remember correctly, Blow your Mind had this mix of v1/v2, and is not correctly imported 👏
