### ISSUE TITLE
id3::frame::EncapsulatedObject: Encoding is inaccessible

### ISSUE THREAD

**Issue by uklotzde** [polyfloyd/rust-id3#97]
It is no longer possible to create instances of `id3::frame::EncapsulatedObject`.

Btw, v1.2.1 introduced breaking changes by adding a new field to this struct.

**Comment by polyfloyd** [comment]
Damn, I must missed that in the review... Thank you for reporting this. I have yanked 1.2.1 from crates.io, we will rethink this approach later when I have more time.

CC @Marekkon5

**Comment by Marekkon5** [comment]
My bad, lemme fix asap
