### ISSUE TITLE
Chapters TOC

### ISSUE THREAD

**Issue by brainrepo** [polyfloyd/rust-id3#99]
Is there a plan to add chapters TOC like in the https://id3.org/id3v2-chapters-1.0#sec3.2?
I'd like to contribute but I am a newbie on rust :(

**Comment by polyfloyd** [comment]
CHAP is implemented, CTOC is not. I would welcome a patch that adds it!

If you would like to give this a shot, you might be able to start out by looking at how CHAP is decoded. Looking at the spec, it does seem like a quite complicated frame, so if you want to pass that's fine too :)

If you (or anyone reading along) would like me to implement this, please attach one or more files that contains such frames.

**Comment by brainrepo** [comment]
I am trying to delve into the code :D in a while I will share with you an example. The file contains 3 chapters with TIT2, a link and an IMAGE per chapter. Also CTOC is present
[testsilence.mp3.zip](https://github.com/polyfloyd/rust-id3/files/9641270/testsilence.mp3.zip)
